remote_theme: jekyll/minima
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

title: Path of Exile

# Build settings
theme: minima

show_excerpts: false # set to true to show excerpts on the homepage